apiVersion: v2
name: daytona
description: A Helm chart for Daytona - Secure Infrastructure for Running AI Code
type: application
version: 0.0.9
appVersion: "v0.116.1-rc.1"
keywords:
  - ai
  - infrastructure
  - security
  - cloud
  - sandbox
home: https://daytona.io
sources:
  - https://github.com/daytonaio/daytona
maintainers:
  - name: Daytona
    email: engineering@daytona.io
dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "22.0.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: minio
    version: "5.4.0"
    repository: "https://charts.min.io"
    condition: minio.enabled
  - name: pgadmin4
    version: "1.50.0"
    repository: "https://helm.runix.net/"
    condition: pgadmin4.enabled
  - name: harbor
    version: "1.18.0"
    repository: "https://helm.goharbor.io"
    condition: harbor.enabled
