{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytona.secretName" . }}-db
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.externalDatabase.password | b64enc }}
{{- end }}
