{{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) }}
{{- if .Values.externalRedis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytona.secretName" . }}-redis
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | b64enc }}
{{- end }}
{{- end }}
