{{- if .Values.services.api.ingress.enabled -}}
{{- $fullName := include "daytona.fullname" . -}}
{{- $svcPort := .Values.services.api.service.port -}}
{{- $hostname := .Values.services.api.ingress.hostname | default .Values.baseDomain -}}
{{- if and .Values.services.api.ingress.className (not (hasKey .Values.services.api.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.services.api.ingress.annotations "kubernetes.io/ingress.class" .Values.services.api.ingress.className}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.services.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.services.api.ingress.className }}
  ingressClassName: {{ .Values.services.api.ingress.className }}
  {{- end }}
  rules:
    {{- if $hostname }}
    - host: {{ tpl $hostname $ | quote }}
      http:
        paths:
          {{- if .Values.services.api.ingress.extraPaths }}
          {{- toYaml .Values.services.api.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.services.api.ingress.path | default "/" }}
            pathType: {{ .Values.services.api.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}-api
                port:
                  number: {{ $svcPort }}
    {{- end }}
    {{- range .Values.services.api.ingress.extraHosts }}
    - host: {{ tpl .name $ | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service:
                name: {{ $fullName }}-api
                port:
                  number: {{ $svcPort }}
    {{- end }}
    {{- if .Values.services.api.ingress.extraRules }}
    {{- toYaml .Values.services.api.ingress.extraRules | nindent 4 }}
    {{- end }}
  {{- if .Values.services.api.ingress.tls }}
  tls:
    {{- if $hostname }}
    {{- $templatedHostname := tpl $hostname $ -}}
    {{- $baseDomain := .Values.baseDomain -}}
    {{- $templatedBaseDomain := tpl $baseDomain $ -}}
    {{- $wildcardBaseDomain := printf "*.%s" $templatedBaseDomain }}
    {{- $tlsSecretName := .Values.services.api.ingress.tlsSecretName | default (printf "%s-tls" $templatedBaseDomain) }}
    - hosts:
        - {{ $templatedHostname | quote }}
        - {{ $wildcardBaseDomain | quote }}
      secretName: {{ $tlsSecretName }}
    {{- end }}
    {{- if .Values.services.api.ingress.extraTls }}
    {{- toYaml .Values.services.api.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
