{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daytona.fullname" . }}-dex
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: dex
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dex.service.port | default 5556 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "daytona.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dex
{{- end }}
