{{- if .Values.services.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "daytona.namespace" . }}
  name: {{ include "daytona.fullname" . }}-jaeger
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
spec:
  type: {{ .Values.services.jaeger.service.type }}
  ports:
    - port: {{ .Values.services.jaeger.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "daytona.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
{{- end }}
