{{- if and .Values.services.runnermanager.enabled .Values.services.runnermanager.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "daytona.serviceAccountName" (dict "Values" .Values "service" "runnermanager" "Chart" .Chart "Release" .Release) }}
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: runnermanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "daytona.serviceAccountName" (dict "Values" .Values "service" "runnermanager" "Chart" .Chart "Release" .Release) }}
subjects:
- kind: ServiceAccount
  name: {{ include "daytona.serviceAccountName" (dict "Values" .Values "service" "runnermanager" "Chart" .Chart "Release" .Release) }}
  namespace: {{ include "daytona.namespace" . }}
{{- end }}