{{- if and .Values.services.runnermanager.enabled .Values.services.runnermanager.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "daytona.serviceAccountName" (dict "Values" .Values "service" "runnermanager" "Chart" .Chart "Release" .Release) }}
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: runnermanager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
{{- end }}