{{- if .Values.services.proxy.ingress.enabled }}
{{- if .Values.services.proxy.ingress.secrets }}
{{- range .Values.services.proxy.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "daytona.namespace" $ }}
  labels:
    {{- include "daytona.labels" $ | nindent 4 }}
    app.kubernetes.io/component: proxy
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
{{- if and .Values.services.proxy.ingress.tls .Values.services.proxy.ingress.selfSigned }}
{{- $proxyHostname := include "daytona.proxyUrl.hostname" . }}
{{- $wildcardHostname := printf "*.%s" $proxyHostname }}
{{- $secretName := printf "%s-tls" $proxyHostname }}
{{- $ca := genCA "daytona-proxy-ca" 365 }}
{{- $cert := genSignedCert $proxyHostname nil (list $proxyHostname $wildcardHostname) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
{{- end }}
