{{- if .Values.services.snapshotManager.enabled -}}
{{- if and .Values.services.snapshotManager.storage.s3.accessKey .Values.services.snapshotManager.storage.s3.secretKey (not .Values.services.snapshotManager.storage.s3.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytona.fullname" . }}-snapshot-manager-s3
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: snapshot-manager
type: Opaque
data:
  accessKey: {{ .Values.services.snapshotManager.storage.s3.accessKey | b64enc | quote }}
  secretKey: {{ .Values.services.snapshotManager.storage.s3.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
