apiVersion: v2
name: daytona-region
description: A Helm chart for Daytona custom region
type: application
version: 0.0.6
appVersion: "v0.132.0"
keywords:
  - ai
  - infrastructure
  - security
  - cloud
  - sandbox
home: https://daytona.io
sources:
  - https://github.com/daytonaio/daytona
maintainers:
  - name: Daytona
    email: engineering@daytona.io
